FROM rustembedded/cross:aarch64-unknown-linux-gnu
RUN dpkg --add-architecture arm64
RUN apt-get update
RUN apt-get install --assume-yes --no-install-recommends libarchive-dev:arm64

ENV PKG_CONFIG=aarch64-linux-gnu-pkg-config
